spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: http://localhost:8080/realms/My-Realm/.well-known/openid-configuration
          jwk-set-uri: http://localhost:8080/realms/My-Realm/protocol/openid-connect/certs

server:
  port: 9191



logging:
  level:
    org:
      springframework: DEBUG